/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 static/models/scene.glb -k -t 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    plant001: THREE.Mesh;
    Circle001: THREE.Mesh;
    NurbsPath006: THREE.Mesh;
    NurbsPath007: THREE.Mesh;
    NurbsPath008: THREE.Mesh;
    NurbsPath009: THREE.Mesh;
    NurbsPath010: THREE.Mesh;
    NurbsPath011: THREE.Mesh;
    Circle002: THREE.Mesh;
    Circle002_1: THREE.Mesh;
    Circle002_2: THREE.Mesh;
    Circle002_3: THREE.Mesh;
    Circle002_4: THREE.Mesh;
    Circle006: THREE.Mesh;
    Circle006_1: THREE.Mesh;
    FrontCameraRing001: THREE.Mesh;
    Circle: THREE.Mesh;
    Circle_1: THREE.Mesh;
    Circle_2: THREE.Mesh;
    KeyboardKeyHole: THREE.Mesh;
    RubberFoot: THREE.Mesh;
    Circle012: THREE.Mesh;
    Circle012_1: THREE.Mesh;
    Circle009: THREE.Mesh;
    Circle009_1: THREE.Mesh;
    Circle003: THREE.Mesh;
    Circle003_1: THREE.Mesh;
    Circle005: THREE.Mesh;
    Circle005_1: THREE.Mesh;
    Circle005_2: THREE.Mesh;
    Circle005_3: THREE.Mesh;
    Circle005_4: THREE.Mesh;
    rubber_duck_toy: THREE.Mesh;
    Desk: THREE.Mesh;
    OfficeChair_1: THREE.Mesh;
    OfficeChair_2: THREE.Mesh;
    OfficeChair_3: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Plane_3: THREE.Mesh;
  };
  materials: {
    ['Material.028']: THREE.MeshStandardMaterial;
    ['Material.030']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Frame.001']: THREE.MeshStandardMaterial;
    HeadPhoneHole: THREE.MeshStandardMaterial;
    USB_C_INSIDE: THREE.MeshStandardMaterial;
    TouchbarBorder: THREE.MeshStandardMaterial;
    Keyboard: THREE.MeshStandardMaterial;
    ['CameraRIngBlack.002']: THREE.MeshStandardMaterial;
    ['Keyboard.001']: THREE.MeshStandardMaterial;
    Key: THREE.MeshStandardMaterial;
    Touchbar: THREE.MeshStandardMaterial;
    DarkRubber: THREE.MeshStandardMaterial;
    HingeBlack: THREE.MeshStandardMaterial;
    HingeMetal: THREE.MeshStandardMaterial;
    SpeakerHole: THREE.MeshStandardMaterial;
    ['Frame.002']: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
    ScreenGlass: THREE.MeshStandardMaterial;
    Rubber: THREE.MeshStandardMaterial;
    DisplayGlass: THREE.MeshStandardMaterial;
    rubber_duck_toy: THREE.MeshStandardMaterial;
    Wall: THREE.MeshStandardMaterial;
    Grey: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
    Chair: THREE.MeshStandardMaterial;
    Default: THREE.MeshStandardMaterial;
    Floor: THREE.MeshStandardMaterial;
  };
  animations: any; // GLTFAction[]
};

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>;

const Office = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/scene.glb') as GLTFResult;

  const texture = useTexture('/textures/baked.jpg');
  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        name="plant001"
        geometry={nodes.plant001.geometry}
        material={textureMaterial}
        position={[1.213, 0.107, -1.665]}
        rotation={[-Math.PI, 0.08, -Math.PI]}
      >
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={textureMaterial} />
        <mesh name="NurbsPath006" geometry={nodes.NurbsPath006.geometry} material={textureMaterial} />
        <mesh name="NurbsPath007" geometry={nodes.NurbsPath007.geometry} material={textureMaterial} />
        <mesh name="NurbsPath008" geometry={nodes.NurbsPath008.geometry} material={textureMaterial} />
        <mesh name="NurbsPath009" geometry={nodes.NurbsPath009.geometry} material={textureMaterial} />
        <mesh name="NurbsPath010" geometry={nodes.NurbsPath010.geometry} material={textureMaterial} />
        <mesh name="NurbsPath011" geometry={nodes.NurbsPath011.geometry} material={textureMaterial} />
      </mesh>
      <group name="Macbook" position={[0.031, 0.735, -1.559]}>
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={textureMaterial} />
        <mesh name="Circle002_1" geometry={nodes.Circle002_1.geometry} material={textureMaterial} />
        <mesh name="Circle002_2" geometry={nodes.Circle002_2.geometry} material={textureMaterial} />
        <mesh name="Circle002_3" geometry={nodes.Circle002_3.geometry} material={textureMaterial} />
        <mesh name="Circle002_4" geometry={nodes.Circle002_4.geometry} material={textureMaterial} />
        <group name="Bottom" position={[0, -0.009, 0]}>
          <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={textureMaterial} />
          <mesh name="Circle006_1" geometry={nodes.Circle006_1.geometry} material={textureMaterial} />
        </group>
        <mesh
          name="FrontCameraRing001"
          geometry={nodes.FrontCameraRing001.geometry}
          material={textureMaterial}
          position={[-0.003, 0.364, -0.3]}
        />
        <group name="Keyboard" position={[-0.219, -0.003, -0.154]}>
          <mesh name="Circle" geometry={nodes.Circle.geometry} material={textureMaterial} />
          <mesh name="Circle_1" geometry={nodes.Circle_1.geometry} material={textureMaterial} />
          <mesh name="Circle_2" geometry={nodes.Circle_2.geometry} material={textureMaterial} />
        </group>
        <mesh
          name="KeyboardKeyHole"
          geometry={nodes.KeyboardKeyHole.geometry}
          material={textureMaterial}
          position={[-0.219, -0.003, -0.154]}
        />
        <mesh
          name="RubberFoot"
          geometry={nodes.RubberFoot.geometry}
          material={textureMaterial}
          position={[-0.222, -0.014, 0.146]}
        />
        <group name="ScreenHinge" position={[0, -0.004, -0.196]}>
          <mesh name="Circle012" geometry={nodes.Circle012.geometry} material={textureMaterial} />
          <mesh name="Circle012_1" geometry={nodes.Circle012_1.geometry} material={textureMaterial} />
        </group>
        <group name="SpeakerLeft" position={[-0.279, 0.001, 0.011]}>
          <mesh name="Circle009" geometry={nodes.Circle009.geometry} material={textureMaterial} />
          <mesh name="Circle009_1" geometry={nodes.Circle009_1.geometry} material={textureMaterial} />
        </group>
        <group name="SpeakerRight" position={[0.227, 0.001, 0.011]}>
          <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={textureMaterial} />
          <mesh name="Circle003_1" geometry={nodes.Circle003_1.geometry} material={textureMaterial} />
        </group>
        <group name="Top" position={[0, -0.009, -0.193]} rotation={[1.311, 0, 0]}>
          <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={textureMaterial} />
          <mesh name="Circle005_1" geometry={nodes.Circle005_1.geometry} material={textureMaterial} />
          <mesh name="Circle005_2" geometry={nodes.Circle005_2.geometry} material={textureMaterial} />
          <mesh name="Circle005_3" geometry={nodes.Circle005_3.geometry} material={textureMaterial} />
          <mesh name="Circle005_4" geometry={nodes.Circle005_4.geometry} material={textureMaterial} />
        </group>
      </group>
      <mesh
        name="rubber_duck_toy"
        geometry={nodes.rubber_duck_toy.geometry}
        material={textureMaterial}
        position={[-0.623, 0.717, -1.559]}
        rotation={[0, 1.084, 0]}
      />
      <mesh name="Desk" geometry={nodes.Desk.geometry} material={textureMaterial} position={[-0.618, 0, -1.677]} />
      <group name="OfficeChair" position={[-0.303, 0, -0.492]} rotation={[-Math.PI / 2, 0, 2.239]}>
        <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={textureMaterial} />
        <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={textureMaterial} />
        <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={textureMaterial} />
      </group>
      <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={textureMaterial} />
      <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={textureMaterial} />
      <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={textureMaterial} />
    </group>
  );
};

useGLTF.preload('/models/scene.glb');

export default Office;

